## LOAD THE DATA

In [30]:
import pandas as pd

df_demo = pd.read_csv('df_final_demo.txt')
df_web_1 = pd.read_csv('df_final_web_data_pt_1.txt')
df_web_2 = pd.read_csv('df_final_web_data_pt_2.txt')
df_experiment = pd.read_csv('df_final_experiment_clients.txt')

## VIEW DEMOGRAPHICS (The Client Info)

In [31]:
print("DEMOGRAPHICS DATASET")
display(df_demo.head()) # Shows the first 5 rows and all columns

DEMOGRAPHICS DATASET

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

## VIEW WEB DATA 1(The User Journey)

In [32]:
print("WEB DATASET (Part 1)")
display(df_web_1.head())

WEB DATASET (Part 1)

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

## VIEW WEB DATA2 (The User Journey)

In [33]:
print("WEB DATASET (Part2)")
display(df_web_2.head())

WEB DATASET (Part2)

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58

## VIEW EXPERIMENT ROSTER (The Test Groups)

In [34]:
print("EXPERIMENT CLIENTS")
display(df_experiment.head())

EXPERIMENT CLIENTS

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [35]:
print(f"Demographics: {df_demo.shape}")
print(f"Web Part 1:   {df_web_1.shape}")
print(f"Web Part 2:   {df_web_2.shape}")
print(f"Experiment:   {df_experiment.shape}")

Demographics: (70609, 9)
Web Part 1:   (343141, 5)
Web Part 2:   (412264, 5)
Experiment:   (70609, 2)

## MERGE WEB DATA PARTS

In [36]:

# We stack the two web parts on top of each other

df_web = pd.concat([df_web_1, df_web_2], axis=0)

## VIEW MERGED WEB DATA

In [37]:
print("WEB DATASET ")
display(df_web.head())

WEB DATASET

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [38]:
print(f"Web Part :   {df_web.shape}")

Web Part :   (755405, 5)

## MERGE EVERYTHING INTO MASTER

In [39]:
# Merge web data with experiment roster first, then add demographics

df_merged = pd.merge(df_web, df_experiment, on='client_id', how='left')

df_final = pd.merge(df_merged, df_demo, on='client_id', how='left')

In [40]:
print("FINAL DATASET ")
display(df_final.head())

FINAL DATASET

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0

In [41]:
print(f"Final Dataset :   {df_final.shape}")

Final Dataset :   (755405, 14)

##  HANDLE MISSING VARIATIONS

In [42]:
# If a client isn't in 'Test' or 'Control', they aren't part of the experiment.

df_final = df_final.dropna(subset=['Variation'])

In [43]:
df_final.shape

(321309, 14)

## CREATE SEGMENT COLUMNS

In [44]:
# High Balance: Top 25% of the 'bal' column

balance_threshold = df_final['bal'].quantile(0.75)
df_final['is_high_balance'] = df_final['bal'] >= balance_threshold

In [45]:
# This should show roughly 25% True and 75% False
print(df_final['is_high_balance'].value_counts(normalize=True))

is_high_balance
False    0.750069
True     0.249931
Name: proportion, dtype: float64

In [46]:
# Multi-Account: Clients with more than 2 accounts

df_final['is_multi_account'] = df_final['num_accts'] > 2

## Check

In [47]:

# View the first 5 rows
display(df_final.head())

# View 5 random rows (great for spotting weird data)
display(df_final.sample(5))

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,is_high_balance,is_multi_account
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0,True,False
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0,True,False
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0,True,False
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0,True,False
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0,True,False

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,is_high_balance,is_multi_account
360481,9577290,495252412_3924882680,755487100_20186855210_88290,confirm,2017-05-29 14:50:14,Control,8.0,106.0,30.0,F,2.0,56645.30,2.0,5.0,False,False
23262,9213605,5729224_51954520220,602508523_65849911870_570621,step_3,2017-04-19 11:19:05,Test,16.0,197.0,29.0,F,3.0,87757.70,1.0,4.0,False,True
446319,9270161,380209154_17464107165,925330988_57795020260_176757,step_2,2017-06-20 19:14:33,Control,23.0,286.0,53.0,M,3.0,593175.20,6.0,9.0,True,True
189689,5800414,32230494_73636604388,249014031_27820877240_328024,step_1,2017-04-23 16:16:16,Test,12.0,144.0,29.5,M,2.0,147441.82,4.0,7.0,False,False
133821,4767003,685965231_19476758321,311156221_31171902819_473882,step_3,2017-03-29 11:09:37,Control,7.0,85.0,26.5,U,2.0,47534.19,6.0,9.0,False,False

## Check column names, null counts, and data types

In [57]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 321207 entries, 0 to 637535
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   client_id         321207 non-null  int64
 1   visitor_id        321207 non-null  object
 2   visit_id          321207 non-null  object
 3   process_step      321207 non-null  object
 4   date_time         321207 non-null  object
 5   Variation         321207 non-null  object
 6   clnt_tenure_yr    321207 non-null  float64
 7   clnt_tenure_mnth  321207 non-null  float64
 8   clnt_age          321195 non-null  float64
 9   gendr             321207 non-null  object
 10  num_accts         321207 non-null  float64
 11  bal               321207 non-null  float64
 12  calls_6_mnth      321207 non-null  float64
 13  logons_6_mnth     321207 non-null  float64
 14  is_high_balance   321207 non-null  bool
 15  is_multi_account  321207 non-null  bool
dtypes: bool(2), float64(7), int64(1), object(6)
memory usage: 37.4+ MB

## Check the shape (How many rows and columns total?)

In [58]:
print(f"Dataset has {df_final.shape[0]} rows and {df_final.shape[1]} columns.")

Dataset has 321207 rows and 16 columns.

## See the mean, min, max, and quartiles for numerical columns

In [59]:
df_final.describe()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,num_accts,bal,calls_6_mnth,logons_6_mnth
count,3.212070e+05,321207.000000,321207.000000,321195.000000,321207.000000,3.212070e+05,321207.000000,321207.000000
mean,5.009753e+06,12.176372,152.133095,48.553511,2.262952,1.622097e+05,3.236863,6.275109
std,2.872600e+06,6.963097,83.209386,15.645588,0.541528,3.494719e+05,2.193654,2.179721
min,5.550000e+02,2.000000,33.000000,17.000000,1.000000,2.378944e+04,0.000000,3.000000
25%,2.514553e+06,6.000000,82.000000,34.500000,2.000000,4.105887e+04,1.000000,4.000000
50%,5.051667e+06,11.000000,138.000000,50.000000,2.000000,6.924049e+04,3.000000,6.000000
75%,7.468377e+06,16.000000,193.000000,61.000000,2.000000,1.514930e+05,6.000000,9.000000
max,9.999832e+06,55.000000,669.000000,96.000000,7.000000,1.632004e+07,6.000000,9.000000

## How many people are in Test vs Control?

In [60]:
print(df_final['Variation'].value_counts())

Variation
Test       177787
Control    143420
Name: count, dtype: int64

## How many are High Balance (the column you created)?

In [61]:
print(df_final['is_high_balance'].value_counts())

is_high_balance
False    240902
True      80305
Name: count, dtype: int64

## Check if there are any clients who have NO balance data (NaN)

In [62]:
print(df_final['bal'].isnull().sum())

0

## Remove the 102 rows where balance is missing

In [63]:
df_final = df_final.dropna(subset=['bal'])

## Verify it's now 0

In [64]:
print(f"Missing balances after cleaning: {df_final['bal'].isnull().sum()}")

Missing balances after cleaning: 0

## Save the master file for Iffah to use in her notebook

In [65]:
df_final.to_csv('vanguard_master_cleaned.csv', index=False)
print("File exported and cleaned! Ready for Iffah.")

File exported and cleaned! Ready for Iffah.